name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
        r-version: ['3.5.3', '3.6.3', '4.0.1']

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Use R ${{ matrix.r-version }}
      uses: r-lib/actions/setup-r@v1
      with:
        r-version: ${{ matrix.r-version }}

    - name: Install R dependencies
      run: Rscript -e "install.packages('jsonlite', repos='https://cloud.r-project.org/', lib = .Library)"

    - name: npm install and test
      run: |
        npm install
        npm test
      env:
        CI: true
